### ISSUE TITLE
问个问题可以吗

### ISSUE THREAD

**Issue by buzai** [rozx/kindlelight#1]
加入我有个文件夹，里面都是mobi文件要怎么才能把这些文件的中的封面标题作者这些信息都读取出来呢

**Comment by rozx** [comment]
嗯...这个是不行的，这个Project主要是从wenku8把轻小说下载下来自动转换成mobi各种而已，并不能直接读取mobi文件。
如果需要的话可以直接来我网站使用在线版本：http://kindle.heavyskymobile.com

**Comment by buzai** [comment]
@rozx  谢谢啊
